platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.6"

inputs:
- name: ci-web

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    go version
    find .
    ./ci-web/ci/tasks/build.sh
