platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.6"

inputs:
- name: repo
  path: ./src/github.com/dnem/ci-web

outputs:
- name: binary

run:
  path: sh
  args:
  - ./src/github.com/dnem/ci-web/ci/tasks/build.sh
