platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.6"

inputs:
- name: ci-web
  path: ./src/github.com/dnem/ci-web

run:
  path: sh
  args:
    - ./src/github.com/dnem/ci-web/ci/tasks/unit.sh
