resources:
- name: ci-web
  type: git
  source:
    uri: https://github.com/dnem/ci-web
    branch: master
  check_every: 30s
- name: cf-dev
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space-dev}}
    skip-cert-check: false

jobs:
- name: build-ci-web
  serial: true
  public: true
  plan:
    - get: repo
      resource: ci-web
      trigger: true
    - task: build
      file: repo/ci/tasks/build.yml
- name: deploy-dev
  serial: true
  public: false
  plan:
    - aggregate:
      - get: repo
        resource: ci-web
        passed: [ build-ci-web ]
        trigger: true
    - put: cf-dev
      params:
        manifest: repo/manifest-dev.yml
        path: binary/ci-web
        current_app_name: ci-web-dev
