resources:
- name: ci-web
  type: git
  source:
    uri: https://github.com/dnem/ci-web
    branch: master

jobs:
- name: test-ci-web
  serial: true
  public: true
  plan:
  - get: ci-web
    trigger: true
  - task: unit
    file: ci-web/ci/tasks/unit.yml

- name: build-ci-web
  serial: true
  public: true
  plan:
    - get: ci-web
      passed: [ test-ci-web ]
      trigger: true
    - task: build
      file: ci-web/ci/tasks/build.yml
