resources:
- name: ci-web
  type: git
  source:
    uri: https://github.com/dnem/ci-web
    branch: master
  check_every: 30s

jobs:
- name: build-ci-web
  serial: true
  public: true
  plan:
    - get: repo
      resource: ci-web
      trigger: true
    - task: build
      file: repo/ci/tasks/build.yml
    - put: binary
      params:
        file: binary/ci-web
